version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_example'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)    
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025 #web-ui
      - 1025:1025 #smtp server
       
volumes:
  my-db: